robot:
  name: blueboat
  environment: real
  localization: real

description:
  package: blueboat_description
  xacro: urdf/blueboat.urdf.xacro

ros2_control:
  params_package: blueboat_description
  params: config/ros2_control_params.yaml

diagnostics:
  params_package: sura_diagnostics
  params: config/blueboat_diagnostics.yaml

cameras:
  down_camera:
    enabled: false
    aruco: false

imu:
  raw_imu_topic: controller/imu_broadcaster/imu
  filtered_imu_topic: sensors/imu
  mag_topic: magnetometer_broadcaster/mag

localization:
  enabled: true
  launch_package: sura_localization
  launch_file: surface_fastlio.launch.py
  publish_tf: true
  frame_convention: ned
