robot:
  name: bluerov
  environment: real
  localization: real

description:
  package: bluerov_description
  xacro: urdf/bigblue.urdf.xacro

ros2_control:
  params_package: bluerov_description
  params: config/ros2_control_params_bigblue.yaml

diagnostics:
  params_package: sura_diagnostics
  params: config/bluerov_diagnostics.yaml

cameras:
  down_camera:
    enabled: false
    driver: usb_cam
    aruco: false
  front_camera:
    enabled: false
    driver: usb_cam
    aruco: false
  right_camera:
    enabled: false
    driver: gstreamer
    aruco: false

imu:
  raw_imu_topic: controller/imu_broadcaster/imu
  filtered_imu_topic: sensors/imu
  mag_topic: controller/magnetometer_broadcaster/mag
  orientation_yaw_stddev_deg: 40.0

localization:
  enabled: true
  launch_package: sura_localization
  launch_file: cirtesu_auv_localization.launch.py
  config_package: sura_localization
  config_file: config/cirtesu_auv_localization.yaml
  publish_tf: true
  datum:
    # latitude: 39.994335199497364
    # longitude: -0.07400607762331379
    # heading: 0.0
    latitude: 39.9944
    longitude: -0.0741
    heading: 0.0
